[project]
name = "regmonkey_repository_document"
version = "2.0.0"
description = "document templates for packagge development"
authors = ["Ryo Nakagami <nakagamiryo0901@gmail.com>"]
license = "MIT"

[dependencies]
os = { ubuntu >= "20.04", linux >= "5.4", macos >= "10.15", darwin >= "20.0.0" }
bash = { version >= "5.0" }
poetry = { version >= "1.6" }
pyenv = { git = "https://github.com/pyenv/pyenv" }
regmonkey_repository_document = { git = "https://github.com/RyoNakagami/regmonkey_repository_document" }
regmonkey_gitignore = { git = "https://github.com/RyoNakagami/regmonkey_gitignore" }